version: "3"
services:
  
  postgres:
    container_name: postgres
    image: postgres:10.16
    ports:
      - "5432:5432"
    volumes: 
      - ./postgresdata:/var/lib/postgresql/data
      - .dbinit.sql:/docker-entrypoint-initdb.d/dbinit.sql
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: raju.123
      POSTGRES_DB: LMSA-DB

   
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:4.18
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: raju.123
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "5050:80"
    

    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres

  lsma-app:
    container_name: LMSA-APP
    build:
      context: .
      dockerfile: .Dockerfile
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:raju.123@my-server:5432/LMSA-DB
      NODE_ENV: development
      PORT: 8080
    ports:
      - "8080:8080"
volumes:
    db-data:
    pgadmin-data:
     
